# Generated by Django 4.1 on 2022-08-22 07:34

import bills.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('CR', 'Created'), ('DF', 'Deficit'), ('CK', 'Check'), ('FN', 'Finalized')], max_length=2)),
                ('user_extra_description', models.TextField()),
                ('staff_extra_description', models.TextField()),
                ('photo', models.ImageField(upload_to='', validators=[bills.models.max_size_validator])),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='services.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('wage', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='services.wage')),
            ],
        ),
    ]
