# Generated by Django 4.1 on 2022-08-22 08:39

import bills.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='photo',
            field=models.ImageField(blank=True, upload_to='', validators=[bills.models.max_size_validator]),
        ),
        migrations.AlterField(
            model_name='bill',
            name='staff_extra_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='state',
            field=models.CharField(blank=True, choices=[('CR', 'Created'), ('DF', 'Deficit'), ('CK', 'Check'), ('FN', 'Finalized')], default='CR', max_length=2),
        ),
        migrations.AlterField(
            model_name='bill',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bill',
            name='user_extra_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='wage',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='services.wage'),
        ),
    ]
