# Generated by Django 4.1 on 2022-08-22 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_alter_bill_photo_alter_bill_staff_extra_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'permissions': [('only_check_bills', 'can see only bills with check status')]},
        ),
    ]
