# Generated by Django 4.1 on 2022-08-22 19:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_alter_bill_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False),
        ),
    ]
